services:
  # Node.js application service
  node-app:
    build: .
    container_name: node-app
    ports:
      - "9003:9003"
    environment:
      - MONGO_URI=mongodb://brrsoftwares:Welcome1@mongo-container:27017/iscadm-dev?authSource=admin
      - ELASTICSEARCH_HOST=elastic
      - ELASTICSEARCH_PORT=9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Welcome1
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
      - BASE_URL=http://192.168.1.60:9003
      - MONGO_USER=brrsoftwares
      - MONGO_PASSWORD=Welcome1
      - MONGODB_IP=mongo-container
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=iscadm-dev
    depends_on:
      - redis-container
      - elastic
      - mongo-container
    restart: unless-stopped

  # Elasticsearch service
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Welcome1
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"  # Exposing Elasticsearch on port 9200
    restart: unless-stopped

  # Redis service
  redis-container:
    image: redis
    container_name: redis-container
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"  # Exposing Redis on port 6379
    restart: unless-stopped

  # MongoDB service
  mongo-container:
    image: mongo:8.0
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brrsoftwares
      - MONGO_INITDB_ROOT_PASSWORD=Welcome1
      - MONGO_INITDB_DATABASE=iscadm-dev
    ports:
      - "27017:27017"  # Exposing MongoDB on port 27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "-u", "brrsoftwares", "-p", "Welcome1", "--authenticationDatabase", "admin", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo_data:
